spring.application.name=SB-EMS-SERVICE

# Embedded Tomcat port number
server.port=1111

# Database Connection Properties
spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Application Properties

pms.save.success="SUCCESS : Product Object Saved"
pms.save.fail="FAILED : DB Error"

pms.update.success="SUCCESS : Product Object Updated"
pms.update.fail="FAILED : DB Error"

pms.delete.success="SUCCESS : Product Object Deleted"
pms.delete.fail="FAILED : Product Not Found"

pms.findall.fail="FAILED : Unable to Fetch Products"

pms.db.fail="FAILED : Database Error"

eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true