spring.application.name=SB-EMS

#Embedded Tomcat port number
server.port=1233

#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Application Properties
ems.save.success="SUCCESS :Employee Object Saved"
ems.save.fail="FAILED : DB Error"

ems.update.success = "SUCCESS :Employee Object Updated"
ems.update.fail="FAILED : DB Error"

ems.delete.success = "SUCCESS :Employee Object deleted"
ems.delete.failed="FAILED : Employee not Found"