spring.application.name=SB-DMS


server.port=2223

spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

dms.save.success=Department Saved Successfully
dms.save.fail=Department Save Failed

dms.update.success=Department Updated Successfully
dms.update.fail=Department Update Failed

dms.delete.success=Department Deleted Successfully
dms.delete.fail=Department Delete Failed

dms.findall.fail=No Departments Found

dms.invalid.department-details=Invalid Department Details

dms.db.failed=Database Operation Failed



eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true